Repository sky-uk/anticipy, pull requests merged in 2018-10, with the labels that each got.

#50 Set up travis
  .travis.yml
  anticipy/forecast.py
  anticipy/forecast_models.py
  setup.py
  tests/test_forecast.py
  tests/test_forecast_model.py
Labels: CI, bug, clean up

#55 7 pep8
  .travis.yml
  anticipy/app.py
  anticipy/forecast.py
  anticipy/forecast_models.py
  anticipy/forecast_plot.py
  anticipy/model_utils.py
  anticipy/utils_test.py
  docs/source/conf.py
  setup.py
  tests/__init__.py
  tests/test_forecast.py
  tests/test_forecast_model.py
  tests/test_forecast_plot.py
  tests/test_model_utils.py
Labels: clean up

#52 Fixed typos in docs
  README.md
  docs/Makefile
  docs/source/conf.py
  docs/source/faq.rst
  docs/source/index.rst
  docs/source/overview.rst
  docs/source/tutorial.rst
Labels: docs

#71 68 path optional plot forecast
  anticipy/app.py
  anticipy/forecast_plot.py
  docs/source/tutorial.rst
  tests/test_forecast_plot.py
Labels: enhancement

#73 Fix documentation issues
  anticipy/forecast.py
  anticipy/forecast_models.py
  anticipy/forecast_plot.py
  anticipy/model_utils.py
  docs/source/overview.rst
  docs/source/tutorial.rst
  pypi-description.md
  setup.py
Labels: docs

#76 Prepare for release 0.1.2
  setup.py
Labels: release

#85 Plotting: reduced space between subplots
  anticipy/forecast_plot.py
Labels: enhancement
